name: Build and Test

on:
  push:
    branches:
      - main
    pull_requests:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'oracle'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install